name: pmsn20232
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_core: ^2.21.0
  youtube_player_flutter: ^8.1.2
  flutter_rating_bar: ^4.0.1
  table_calendar: ^3.0.9
  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.2.1
  day_night_switcher: ^0.2.0+1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/.
